---
title: "portfolio3"
output: html_document
---

## 라이브러리, 데이터로드 
```{r, message=FALSE, warning=FALSE}
library(dplyr)
library(tidyr)
library(tibble)
library(recommenderlab)
library(reshape2)
library(data.table)
library(ggplot2)

rating<-read.csv("/home/kmj/movie/ratings.csv")
movies<-read.csv("/home/kmj/movie/movies.csv",header = TRUE)
```

## 데이터 전처리 
```{r}
movie<-rating %>%
  left_join(movies,by="movieId") %>%
  select(userId,rating,title)

movie<-movie[-c(17820,80597,4748,11452),] #중복값제거
# 17450, 17820
# 80406, 80597
# 4591, 4748
# 11242, 11452

movie_mat<-spread(movie,title,rating) %>%
  remove_rownames() %>%
  column_to_rownames(var="userId")

movie_rrm <- as(as(movie_mat, "matrix"), "realRatingMatrix") #610x9719 610명의 사용자, 9719개의 영화
```

## EDA
```{r}
#EDA
#평점 값 탐구
vector_rating<-as.vector(movie_rrm@data)
unique(vector_rating)
table_ratings<-table(vector_rating)
typeof(table_ratings)
df_ratings<-as.data.frame(table_ratings)
df_ratings<-subset(df_ratings,vector_rating!=0) #0값 제거
options("scipen" = 100)
ggplot(data=df_ratings,aes(x=vector_rating,y=Freq))+geom_bar(stat="identity") #분포 확인

#영화 별 관람횟수 조회 
view_per_movie<-colCounts(movie_rrm)
df_view_per_movie<-data.frame(movie=names(view_per_movie),views=view_per_movie)
rownames(df_view_per_movie)<-NULL #로우이름제거 
head(df_view_per_movie)
df_view_per_movie<-df_view_per_movie %>% #가장많은 본 횟수대로 정렬
  arrange(desc(views))
df_view_per_movie %>% #하나의 영화별 관람횟수 평균 약 10회
  summarise(mean(views))
ggplot(data=df_view_per_movie[1:5,],aes(x=movie,y=views))+geom_bar(stat="identity")

#평균 평점 탐색
avg_rating<-colMeans(movie_rrm)

table_avg_rating<-table(avg_rating) #평균 평점 그 자체의 분포확인
df_table_avg_rating<-as.data.frame(table_avg_rating)
df_table_avg_rating<-df_table_avg_rating %>%
  arrange(desc(Freq))

df_avg_rating<-data.frame(movie=names(avg_rating),avg=avg_rating) #각 영화의 평균 평점
rownames(df_avg_rating)<-NULL
df_avg_rating<-df_avg_rating %>%
  arrange(desc(avg))
head(df_avg_rating)
ggplot(data=df_avg_rating[1:5,],aes(x=movie,y=avg))+geom_bar(stat="identity")

#사용자별 영화관람 횟수
view_per_user<-rowCounts(movie_rrm)
df_view_per_user<-data.frame(userid=names(view_per_user),view=view_per_user)
row.names(df_view_per_user)<-NULL
head(df_view_per_user)
df_view_per_user %>% #사용자별 평균 관람횟수.. 약 165회
  summarise(mean(view))
```

## 협업필터링
데이터전처리
```{r}
#영화를 165편 이상 평가한 사용자, 적어도 10회 이상 시청된 영화로 데이터처리
movie_rrm<-movie_rrm[rowCounts(movie_rrm)>=165, colCounts(movie_rrm)>=10] #159x2269 159명의 사용자, 2269개의 영화

movie_rrm_norm<-normalize(movie_rrm) # 정규화
movie_rrm_watched<-binarize(movie_rrm, minRating=0.5)  
#최저평점인 0.5이상인 경우를 모두 1로 정의하는 매트릭스=즉 평가한 모든 영화에 대해서는 1로 정의함

rating_eval <- evaluationScheme(movie_rrm, method="split", train=0.7, given=5)
```


## IBCF
```{r}
ibcf_model <- Recommender(getData(rating_eval, "train"), method = "IBCF", param=list(k=30))
ibcf_pred <- predict(ibcf_model, getData(rating_eval, "known"), n=6) #6개를 추천해주겠음
recc_user_1<-ibcf_pred@items[[1]] #사용자1에게 추천된 아이템
movie_user_1<-ibcf_pred@itemLabels[recc_user_1] #사용자1에게 추천된 영화추출
head(as(ibcf_pred,"list"))

####data table로 보여주는 작업
ibcf_pred_list<-as(ibcf_pred,"list")
user_id<-names(ibcf_pred_list) #리스트 이름 가져오기=user_id 가져오기
ibcf_df<-data.frame(matrix(nrow=48,ncol=6)) #빈 df생성 

for(i in 1:48){
  for(j in 1:6){
    if(identical(ibcf_pred_list[[i]],character(0))){ #character(0)인 부분이 있어서 판별
      ibcf_df[i,]<-NA
    } 
    else{
      ibcf_df[i,j]<-unlist(ibcf_pred_list[i],use.names = FALSE)[j]
    }
  }
}
rownames(ibcf_df)=user_id
ibcf_df %>%
  DT::datatable()

#많이 추천된 영화순으로 정렬
trans_ibcf_df<-t(ibcf_df)
ibcf_item_sort<-sort(factor(table(trans_ibcf_df)),decreasing = TRUE)
ibcf_sort_df<-data.frame(movie=names(ibcf_item_sort),count=ibcf_item_sort)
row.names(ibcf_sort_df)<-NULL
head(ibcf_sort_df)
```

```{r}
```

```{r}
```

```{r}
```